- name: "Creates Directory"
  file:
    path: ~/web
    state: directory

- name: "extract backend files"
  unarchive:
    src: files/artifact.tar.gz
    dest: ~/web

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: latest

- name: "Stopping default pm2"
  shell: |
    pm2 stop default

- name: "Start backend server"
  shell: |
    pm2 start npm -- start
